/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author GUILLO
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        caja = new javax.swing.JTextField();
        caja1 = new javax.swing.JTextField();
        result = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        suma = new javax.swing.JButton();
        rest = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        div = new javax.swing.JButton();
        pot = new javax.swing.JButton();
        raiz = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        arcos = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        arsen = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        artan = new javax.swing.JButton();
        cot = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        csc = new javax.swing.JButton();
        log = new javax.swing.JButton();
        sec = new javax.swing.JButton();
        fact = new javax.swing.JButton();
        per = new javax.swing.JButton();
        com = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        caja.setMinimumSize(new java.awt.Dimension(80, 22));
        caja.setPreferredSize(new java.awt.Dimension(80, 22));
        caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaActionPerformed(evt);
            }
        });
        jPanel3.add(caja);

        caja1.setPreferredSize(new java.awt.Dimension(80, 22));
        caja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja1ActionPerformed(evt);
            }
        });
        jPanel3.add(caja1);

        result.setPreferredSize(new java.awt.Dimension(80, 22));
        jPanel3.add(result);

        jPanel4.setLayout(new java.awt.GridLayout(10, 2, 5, 5));

        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        jPanel4.add(suma);

        rest.setText("-");
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });
        jPanel4.add(rest);

        mul.setText("*");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });
        jPanel4.add(mul);

        div.setText("/");
        jPanel4.add(div);

        pot.setText("^");
        jPanel4.add(pot);

        raiz.setText("sqrt");
        jPanel4.add(raiz);

        cos.setText("cos");
        jPanel4.add(cos);

        arcos.setText("arcos");
        jPanel4.add(arcos);

        sin.setText("sin");
        jPanel4.add(sin);

        arsen.setText("arsen");
        jPanel4.add(arsen);

        tan.setText("tan");
        jPanel4.add(tan);

        artan.setText("artan");
        jPanel4.add(artan);

        cot.setText("cot");
        jPanel4.add(cot);

        pi.setText("π");
        jPanel4.add(pi);

        csc.setText("csc");
        jPanel4.add(csc);

        log.setText("log");
        jPanel4.add(log);

        sec.setText("sec");
        jPanel4.add(sec);

        fact.setText("!");
        jPanel4.add(fact);

        per.setText("nPr");
        jPanel4.add(per);

        com.setText("nCr");
        jPanel4.add(com);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaActionPerformed

    private void cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton arcos;
    public javax.swing.JButton arsen;
    public javax.swing.JButton artan;
    public javax.swing.JTextField caja;
    public javax.swing.JTextField caja1;
    public javax.swing.JButton com;
    public javax.swing.JButton cos;
    public javax.swing.JButton cot;
    public javax.swing.JButton csc;
    public javax.swing.JButton div;
    public javax.swing.JButton fact;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JButton log;
    public javax.swing.JButton mul;
    public javax.swing.JButton per;
    public javax.swing.JButton pi;
    public javax.swing.JButton pot;
    public javax.swing.JButton raiz;
    public javax.swing.JButton rest;
    public javax.swing.JTextField result;
    public javax.swing.JButton sec;
    public javax.swing.JButton sin;
    public javax.swing.JButton suma;
    public javax.swing.JButton tan;
    // End of variables declaration//GEN-END:variables
}
